name: Generate Definitions
on:
  schedule: [{ cron:  '0 */4 * * *' }] # every 4 hrs: https://crontab.guru/#0_*/4_*_*_*
  push:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run scrape-definitions
    - run: bash --version
    - run: |
        mapfile -t nodes < <(git ls-files --others --exclude-standard -- share/node-build)
        echo ${nodes[@]##*/}
