name: Generate Definitions
on:
  schedule: [{ cron:  '0 */4 * * *' }] # every 4 hrs: https://crontab.guru/#0_*/4_*_*_*
  push:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run scrape-definitions
    - run: bash --version
    - id: scraped
      run: |
        nodes=$(git ls-files --others --exclude-standard -- share/node-build |
            while read -r node; do echo "- ${node##*/}"; done)
        echo "::set-output name=nodes::${nodes//$'\n'/'%0A'}"
    - run: echo ${{ steps.scraped.outputs.nodes }}
